### PR TITLE
Migrate aws_c_io0135 and aws_c_common083

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by h-vetinari** [comment]
```
99% tests passed, 2 tests failed out of 647

Total Test time (real) =  45.84 sec

The following tests FAILED:
	638 - h2_sm_acquire_stream (Failed)
	639 - h2_sm_acquire_stream_multiple_connections (Failed)
```

Unfortunately, this PR now blocks the openssl3 migration (though we could rebuild aws-c-cal 0.5.19 for openssl 3, currently only 0.5.20 has it).

Normally I might advocate just skipping those 2 tests, but that depends how crucial we see HTTP2; stream acquisition is a pretty fundamental operation unfortunately...

First error I see in the trace is:
```
[DEBUG] [2022-10-21T15:14:03Z] [00000da4] [task-scheduler] - id=00000176EF134140: Running attempt_connection task with <Running> status
[DEBUG] [2022-10-21T15:14:03Z] [00000da4] [socket] - id=00000176EF132E10 handle=0000000000000258: initializing with domain 1 and type 0
[DEBUG] [2022-10-21T15:14:03Z] [00000da4] [socket] - id=00000176EF132E10 handle=0000000000000258: setting socket options to: keep-alive 0, keep idle 0, keep-alive interval 0, max failed probe count 0
[DEBUG] [2022-10-21T15:14:03Z] [00000da4] [socket] - id=00000176EF132E10 handle=0000000000000258: beginning connect.
[DEBUG] [2022-10-21T15:14:03Z] [00000da4] [socket] - id=00000176EF132E10 handle=0000000000000258: connecting to endpoint 2606:2800:220:1:248:1893:25c8:1946:443.
[TRACE] [2022-10-21T15:14:03Z] [00000da4] [event-loop] - id=00000176EF11B160: subscribing to events on handle 0000000000000258
[TRACE] [2022-10-21T15:14:03Z] [00000da4] [socket] - id=00000176EF132E10 handle=0000000000000258: connection pending, scheduling timeout task
[TRACE] [2022-10-21T15:14:03Z] [00000da4] [event-loop] - id=00000176EF11B160: scheduling task 00000176EF135540 in-thread for timestamp 731046631800
[DEBUG] [2022-10-21T15:14:03Z] [00000da4] [task-scheduler] - id=00000176EF135540: Scheduling (null) task for future execution at time 731046631800
[TRACE] [2022-10-21T15:14:03Z] [00000da4] [event-loop] - id=00000176EF11B160: detected more scheduled tasks with the next occurring at 731046631800, using timeout of 9999.
[TRACE] [2022-10-21T15:14:03Z] [00000da4] [event-loop] - id=00000176EF11B160: waiting for a maximum of 9999 ms
[TRACE] [2022-10-21T15:14:03Z] [00000da4] [event-loop] - id=00000176EF11B160: wake up with 1 events to process.
[TRACE] [2022-10-21T15:14:03Z] [00000da4] [event-loop] - id=00000176EF11B160: invoking handler.
[TRACE] [2022-10-21T15:14:03Z] [00000da4] [socket] - static: connect completion triggered on event-loop 00000176EF11B160
[TRACE] [2022-10-21T15:14:03Z] [00000da4] [socket] - id=00000176EF132E10 handle=0000000000000258: connect completion triggered. Socket has not timed out yet: proceeding with connection
[ERROR] [2022-10-21T15:14:03Z] [00000da4] [socket] - id=00000176EF132E10 handle=0000000000000258: connect completion triggered with error -1073741252
[ERROR] [2022-10-21T15:14:03Z] [00000da4] [socket] - id=00000176EF132E10 handle=0000000000000258: connection error with code 1049
[DEBUG] [2022-10-21T15:14:03Z] [00000da4] [channel-bootstrap] - id=00000176EF0E0060: client connection on socket 00000176EF132E10 completed with error 1049.
[DEBUG] [2022-10-21T15:14:03Z] [00000da4] [channel-bootstrap] - id=00000176EF0E0060: recording bad address 2606:2800:220:1:248:1893:25c8:1946.
```

**Comment by xhochy** [comment]
> Unfortunately, this PR now blocks the openssl3 migration (through https://github.com/conda-forge/aws-c-s3-feedstock/pull/125 -> aws-sdk-cpp -> arrow-cpp -> etc.; though realistically we could also rebuild aws-c-cal 0.5.19 for openssl 3, currently only 0.5.20 has it).

It would be OK to rebuild aws-c-cal 0.5.19 with openssl3. I will probably rebuild aws-c-io 0.13.4 also for the new aws-c-common to minimise the diff to better understand the failure.

**Comment by h-vetinari** [comment]
> I will probably rebuild aws-c-io 0.13.4 also for the new aws-c-common to minimise the diff to better understand the failure.

Actually, I think that's what's necessary. I may have misread the error in https://github.com/conda-forge/aws-c-s3-feedstock/pull/125
```
The reported errors are:
- Encountered problems while solving:
-   - package aws-c-io-0.13.4-h2f1bd44_4 requires aws-c-cal >=0.5.19,<0.5.20.0a0, but none of the providers can be installed
```

At least, rerendering https://github.com/conda-forge/aws-c-cal-feedstockon the new v0.5.19 branch doesn't generate any changes.

**Comment by xhochy** [comment]
`aws-c-common` was separately migrated, let's wait for a fresh PR for aws-c-io

**Pull request closed without merging**
